### PR TITLE
[PFM-1236] Sync fork origin master

### PR DESCRIPTION
**Pull request by beligante**
[PFM-1236](https://thescore.atlassian.net/browse/PFM-1236)

# Breaking Changes

- Spawn supervisor now expects a Keyword list instead of a tuple. 
  - Before: 
   ``` elixir
      def children, do: [
      # ... other supervisors
        {GRPC.Server.Supervisor, {MyCoolEndPoint, @my_grpc_port}}
      ]
  ```
  - Now: 
  ```elixir
      def children, do: [
      # ... other supervisors
        {GRPC.Server.Supervisor, endpoint: MyEndpoint, port: @my_grpc_port, server_enabled: true}
      ]
   ```
- `server_enable` config is no longer defined in the application config, you should pass is as an option when spawning the supervisor, like in the example above
- `adapter_opts` now expects a keyword list instead of a map.
  - Before:
  ```elixir
      [adapter_opts: %{http2_opts: %{keepalive: @keep_alive}}]
  ``` 
  - After:
  ```elixir
      [adapter_opts: [http2_opts: %{keepalive: @keep_alive}]]
  ```

### CODE REVIEW

**Review by Corvillus — APPROVED** [review]
Tests passing 👍

**Review by jwilson-ts — APPROVED** [review]

**Review by jeffutter — APPROVED** [review]
Everything looks good here. 👍  approving pending that testing apps that depend on this have been appropriately vetted with this branch.

**Comment by beligante** [comment]
As peer @jeffutter, we've been testing this on sportsbook and concierge:
- https://github.com/scorebet/sportsbook/pull/692
- https://github.com/scorebet/concierge/pull/304

**Comment by beligante** [comment]
Start to test on edgebook/corebook

https://github.com/scorebet/edgebook/pull/1498

**Review by darrenclark — APPROVED** [review]
🚢

**Pull request merged**
